name: ???
scenario: ???
dataset: ???
training_version: ???

tensor_type: "torch"
device: "gpu"
num_workers: 4

batch_size: 32
ttsplit: { train: 0.9, valid: 0.05, test: 0.05 }
nepochs: 30
lr: 1e-4

origin:  { x: 0, y: 0 }
tile_grid: { x: 3, y: 3 }
tile_size: { x: 16, y: 16 }
batch_domain:  'time'
conform_to_grid: false
upsample_mode: cubic
downsample_mode: cubic

coords: { x: XC, y: YC, z: '' }
input_variables: { sst: sea_surface_temperature }  # , 'sss': sea_surface_salinity, 'ssh': sea_surface_humidity }
variable_ranges: { sst: { min: 2.9963, max: 23.4310 } }
target_variables: [ sst ]
forcing_variables: []



